name: political_think
description: An open-source news project that organizes news into `Confidence`, `Bias`, `Newsworthiness`, and `Contextualization` to tell maximally truthful news in a clear and measurable way.

version: 1.17.2+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  firebase_core: ^3.9.0
  hooks_riverpod: ^2.3.10
  firebase_auth: ^5.0.0
  google_sign_in_web: ^0.12.4+3 # specified since default version doesnt work with wasm
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^5.0.0
  json_serializable: ^6.7.1
  flutter_spinkit: ^5.2.0
  cloud_functions: ^5.0.0
  receive_sharing_intent: ^1.4.5
  modal_bottom_sheet: ^3.0.0-pre
  shared_preferences: ^2.3.3
  uuid: ^4.1.0
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_svg: ^2.0.7
  ogp_data_extract: ^0.1.4
  scroll_to_index: ^3.0.1
  linked_scroll_controller: ^0.2.0
  tuple: ^2.0.2
  equatable: ^2.0.5
  visibility_detector: ^0.4.0+2
  flutter_parsed_text: ^2.2.1
  diffutil_dart: ^4.0.0
  date_count_down: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_joystick: ^0.0.4
  google_fonts: ^6.1.0
  countries_world_map: ^1.1.1
  google_maps_flutter: ^2.10.0
  http: ^1.1.2
  syncfusion_flutter_sliders: ^28.1.36
  syncfusion_flutter_core: ^28.1.36
  country_picker: ^2.0.23
  image_stack: ^2.1.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.8
  flutter_native_splash: ^2.4.4
  timeago: ^3.6.1
  photo_view: ^0.15.0
  flutter_dotenv: ^5.1.0
  animated_text_kit: ^4.2.2
  package_info_plus: ^8.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# building dart 3.5.0 causes an issue that is fixed with this
# there might be a better way to resolve, but we dont use win32 and this works
dependency_overrides: 
  win32: ^5.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/maps/
    - config.env

  fonts:
    - family: Minecart
      fonts:
        - asset: assets/fonts/Minecart_LCD.ttf
    - family: Georgia
      fonts:
        - asset: assets/fonts/georgia.ttf
        - asset: assets/fonts/georgia_bold.ttf
          weight: 700
        - asset: assets/fonts/georgia_italic.ttf
          style: italic
        - asset: assets/fonts/georgia_z.ttf
          weight: 700
          style: italic
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_book.ttf
          weight: 400
        - asset: assets/fonts/avenir_heavy.ttf
          weight: 700
        - asset: assets/fonts/avenir_light.ttf
          weight: 300
        - asset: assets/fonts/avenir_black.ttf
          weight: 900
        - asset: assets/fonts/avenir_regular.ttf
          weight: 500
    

# run this command to regenerate
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_white_on_black.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#0E0E0E" # Set background color for Android adaptive icons
  web:
    generate: true
    image_path: "assets/images/logo_white_on_black.png"
    background_color: "#0E0E0E" # Set background color for web icons
    theme_color: "#0E0E0E" # Optionally, set theme color for web

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF" # White background for light mode
  image: assets/images/logo_black.png # Logo for light mode
  color_dark: "#0E0E0E" # Black background for dark mode
  image_dark: assets/images/logo_white.png # Logo for dark mode
  branding_bottom_padding: 24
  branding: assets/images/prerelease_light.png
  branding_dark: assets/images/prerelease_dark.png
